# Configuración del sitio
title: "Juan Pablo Jaramillo Ormaza"
description: "Médico con 13 años de experiencia | Health Data Scientist en formación | Proyecto: Sistema de alerta temprana de riesgo cardiovascular"
theme: jekyll-theme-cayman

# URL del sitio
baseurl: "/ibm-data-science-portfolio"
url: "https://juanjararpybm.github.io"

# Autor
author:
  name: "Juan Pablo Jaramillo"
  email: "juanjararPYBM@users.noreply.github.com"

# Redes sociales
social:
  github: juanjararPYBM
